# -*- coding: utf-8 -*-
"""Assignment3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KXXCPrXHsAaBN7dhPlbWEl3T3UO4uLhn
"""

print("Welcome to Airway\n")

print("Hello pilot,please give the flight details.")
curht=int(input("What is the current height of the flight in air:"))
height=1000
print("Since,the Present height of the flight is "+str(curht)+".Pilot,we request you to")
if(curht<=height):
    print("Safe to land.")
elif (curht>height and curht<5000):
     print("Bring down to 1000ft.") 
else:
    print("Turn around and try later.")

print("Thank you...")